
CREATE TABLE IF NOT EXISTS public.transaction (
  id UUID PRIMARY KEY, 
  walletId UUID NOT NULL, 
  eventId UUID NOT NULL,
  type VARCHAR(50) NOT NULL, 
  amount NUMERIC(15, 2) NOT NULL, 
  afterBalance NUMERIC(15, 2), 
  status VARCHAR(50) NOT NULL, 
  failingReason TEXT, 
  externalReference VARCHAR, 
  createdAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
  updatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP 
);